---
linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: true

  BorderZero:
    enabled: true
    convention: 0 # or 'none'

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or new_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  IdSelector:
    enabled: false # don't throw notices for every damn ID

  ImportantRule:
    enabled: true # warn about using !important

  # The basenames of @imported SCSS partials should not begin with an underscore and should not include the filename extension.
  ImportPath:
    enabled: true

  Indentation:
    character: tab # or space (default space)
    enabled: true
    width: 1

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 6

  PlaceholderInExtend:
    enabled: true

  PropertyCount:
    enabled: false

  PropertySortOrder:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: false
    allow_element_with_attribute: false # default
    allow_element_with_class: false # default
    allow_element_with_id: false # default

  SelectorDepth:
    enabled: true
    max_depth: 6 # default 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase # or snake_case, camel_case, or BEM, or hyphenated_BEM), or a regex the name must match
    ignored_names: []
    ignored_types: []
    # attribute_convention:
    # class_convention:
    # id_convention:
    # placeholder_convention:

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true # allows p { margin: 0; padding: 0; }

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or no_space, at_least_one_space, aligned

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true # allows you to use extra spaces to align single line blocks

  SpaceBetweenParens:
    enabled: true
    spaces: 1 # default 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefixes:
    enabled: false
    include: []
    exclude: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
